# Generated by Django 3.2.8 on 2021-10-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_github', models.URLField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reviewer', models.CharField(max_length=200)),
                ('assignee', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=128)),
                ('user_req_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='pull_requests.userrequest')),
            ],
        ),
    ]
